import { UserProfile, Post } from '../types';

export const DEMO_PROFILES: UserProfile[] = [
  {
    uid: 'demo1',
    displayName: 'Alex Rivers',
    age: 26,
    bio: 'Serial entrepreneur & Full-stack dev. Building the next gen of neural interfaces. Looking for a marketing wizard.',
    skills: ['Rust', 'TypeScript', 'AI/ML'],
    interests: ['Neural Tech', 'Bio-hacking', 'Crypto'],
    goals: 'Find a co-founder for my next startup',
    country: 'USA',
    city: 'San Francisco',
    experience: 'Ex-Google engineer',
    personalityType: 'Architect',
    commitmentLevel: 'Full-time',
    industries: ['Deep Tech'],
    profilePic: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1000&auto=format&fit=crop',
    coverPhoto: '',
    achievements: [],
    badges: [],
    reputationScore: 98,
    streakCount: 15,
    lastActiveAt: null as any,
    createdAt: null as any,
    socialLinks: {},
    isVisible: true,
    isBot: false,
    projects: [
      { name: 'NeuralLink-Alpha', description: 'Real-time neural interface for gaming.', role: 'Lead Architect' },
      { name: 'MindSync', description: 'Brain-to-brain communication protocol.', role: 'Founder' }
    ],
    portfolioLinks: [],
    startupIdeas: [],
    resume: { shippedProducts: [], sideProjects: [], startupAttempts: [], hackathonWins: ['Winner of 5 hackathons'], buildStreaks: 12 },
    onboarded: true
  },
  {
    uid: 'demo2',
    displayName: 'Sarah Chen',
    age: 24,
    bio: 'Product Designer obsessed with minimal UX. Shipped 3 apps last year. Can help with branding and design system.',
    skills: ['Figma', 'UI/UX', 'Product Strategy'],
    interests: ['Design Systems', 'Social Media', 'SaaS'],
    goals: 'Join a high-growth startup',
    country: 'Canada',
    city: 'Toronto',
    experience: 'Freelance Lead',
    personalityType: 'Designer',
    commitmentLevel: 'Part-time',
    industries: ['EdTech', 'Social'],
    profilePic: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1000&auto=format&fit=crop',
    coverPhoto: '',
    achievements: [],
    badges: [],
    reputationScore: 95,
    streakCount: 8,
    lastActiveAt: null as any,
    createdAt: null as any,
    socialLinks: {},
    isVisible: true,
    isBot: false,
    projects: [
      { name: 'Flux Design System', description: 'Minimalist designer system for modern web apps.', role: 'Lead Designer' }
    ],
    portfolioLinks: [],
    startupIdeas: [],
    resume: { shippedProducts: [], sideProjects: [], startupAttempts: [], hackathonWins: [], buildStreaks: 5 },
    onboarded: true
  },
  {
    uid: 'demo3',
    displayName: 'Marcus Thorne',
    age: 31,
    bio: 'Growth hacker. Scaled a fintech from 0 to 1M users. Looking for a solid technical lead to build a new payment gateway.',
    skills: ['Growth', 'Marketing', 'SQL'],
    interests: ['Fintech', 'Scaling', 'Venture Capital'],
    goals: 'Build a billion dollar company',
    country: 'UK',
    city: 'London',
    experience: 'Growth Lead at Revolut',
    personalityType: 'Commander',
    commitmentLevel: 'Full-time',
    industries: ['Fintech'],
    profilePic: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1000&auto=format&fit=crop',
    coverPhoto: '',
    achievements: [],
    badges: [],
    reputationScore: 92,
    streakCount: 20,
    lastActiveAt: null as any,
    createdAt: null as any,
    socialLinks: {},
    isVisible: true,
    isBot: false,
    projects: [
      { name: 'PayFlow', description: 'B2B payment processing for modern startups.', role: 'Co-founder' }
    ],
    portfolioLinks: [],
    startupIdeas: [],
    resume: { shippedProducts: [], sideProjects: [], startupAttempts: [], hackathonWins: [], buildStreaks: 30 },
    onboarded: true
  },
  {
    uid: 'demo4',
    displayName: 'Elena Vance',
    age: 28,
    bio: 'Backend specialist (Go/Kubernetes). Into distributed systems and high availability. Open to exciting challenges.',
    skills: ['Go', 'Cloud Architecture', 'DevOps'],
    interests: ['Infrastructure', 'Security', 'Open Source'],
    goals: 'Network with fellow builders',
    country: 'Germany',
    city: 'Berlin',
    experience: 'Infrastructure Architect',
    personalityType: 'Logician',
    commitmentLevel: 'Full-time',
    industries: ['DevTools', 'Cloud'],
    profilePic: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1000&auto=format&fit=crop',
    coverPhoto: '',
    achievements: [],
    badges: [],
    reputationScore: 89,
    streakCount: 12,
    lastActiveAt: null as any,
    createdAt: null as any,
    socialLinks: {},
    isVisible: true,
    isBot: false,
    projects: [
      { name: 'Kubeflow Extensions', description: 'Custom plugins for ML workflows on K8s.', role: 'Contributor' }
    ],
    portfolioLinks: [],
    startupIdeas: [],
    resume: { shippedProducts: [], sideProjects: [], startupAttempts: [], hackathonWins: [], buildStreaks: 10 },
    onboarded: true
  },
  {
    uid: 'demo5',
    displayName: 'Kai Suzuki',
    age: 22,
    bio: 'Mobile dev (Swift/React Native). Winner of 5 hackathons. Building a decentralized fitness app.',
    skills: ['Swift', 'Kotlin', 'React Native'],
    interests: ['Fitness Tech', 'Web3', 'AI'],
    goals: 'Find early users and a co-founder',
    country: 'Japan',
    city: 'Tokyo',
    experience: 'Student Entrepreneur',
    personalityType: 'Adventurer',
    commitmentLevel: 'Full-time',
    industries: ['Health', 'Web3'],
    profilePic: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1000&auto=format&fit=crop',
    coverPhoto: '',
    achievements: [],
    badges: [],
    reputationScore: 94,
    streakCount: 45,
    lastActiveAt: null as any,
    createdAt: null as any,
    socialLinks: {},
    isVisible: true,
    isBot: false,
    projects: [
      { name: 'ZenFit', description: 'Decentralized fitness tracker using AR.', role: 'Creator' }
    ],
    portfolioLinks: [],
    startupIdeas: [],
    resume: { shippedProducts: [], sideProjects: [], startupAttempts: [], hackathonWins: ['Winner of 5 hackathons'], buildStreaks: 45 },
    onboarded: true
  },
  {
    uid: 'demo6',
    displayName: 'Olivia Martinez',
    age: 27,
    bio: 'Brand specialist & Content Strategist. I make boring startups cool. 50k+ followers on Twitter.',
    skills: ['Branding', 'Copywriting', 'Publicity'],
    interests: ['SaaS marketing', 'Content creation', 'Lifestyle'],
    goals: 'Collaborate on viral products',
    country: 'USA',
    city: 'Austin',
    experience: 'Brand Strategist',
    personalityType: 'Protagonist',
    commitmentLevel: 'Contract',
    industries: ['Marketing', 'E-commerce'],
    profilePic: 'https://images.unsplash.com/photo-1567532939604-b6c5b0ad2e01?q=80&w=1000&auto=format&fit=crop',
    coverPhoto: '',
    achievements: [],
    badges: [],
    reputationScore: 91,
    streakCount: 5,
    lastActiveAt: null as any,
    createdAt: null as any,
    socialLinks: {},
    isVisible: true,
    isBot: false,
    projects: [
      { name: 'SocialViral', description: 'Analytics for content marketers.', role: 'UI/UX Advisor' }
    ],
    portfolioLinks: [],
    startupIdeas: [],
    resume: { shippedProducts: [], sideProjects: [], startupAttempts: [], hackathonWins: [], buildStreaks: 3 },
    onboarded: true
  },
  {
    uid: 'demo7',
    displayName: 'David Wu',
    age: 30,
    bio: 'Hardware engineer with a passion for IoT. Building a smart hydroponic system. Need a mobile dev partner.',
    skills: ['C++', 'Embedded C', 'Electrical Engineering'],
    interests: ['IoT', 'Sustainability', 'Robotics'],
    goals: 'Productize my prototype',
    country: 'Singapore',
    city: 'Singapore',
    experience: 'IoT Architect',
    personalityType: 'Virtuoso',
    commitmentLevel: 'Full-time',
    industries: ['Hard Tech', 'AgriTech'],
    profilePic: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=1000&auto=format&fit=crop',
    coverPhoto: '',
    achievements: [],
    badges: [],
    reputationScore: 97,
    streakCount: 25,
    lastActiveAt: null as any,
    createdAt: null as any,
    socialLinks: {},
    isVisible: true,
    isBot: false,
    projects: [
      { name: 'SmartHydro', description: 'Autonomous gardening systems for small apartments.', role: 'Founder' }
    ],
    portfolioLinks: [],
    startupIdeas: [],
    resume: { shippedProducts: [], sideProjects: [], startupAttempts: [], hackathonWins: ['IoT Innovator Award'], buildStreaks: 20 },
    onboarded: true
  },
  {
    uid: 'demo8',
    displayName: 'Sophia Loren',
    age: 26,
    bio: 'Legal-tech enthusiast. Ex-lawyer turned coder. Building a bridge between law and automation.',
    skills: ['Python', 'Django', 'Legal Research'],
    interests: ['LegalTech', 'AI ethics', 'Regulation'],
    goals: 'Disrupt the legal industry',
    country: 'Italy',
    city: 'Milan',
    experience: 'Associate Attorney',
    personalityType: 'Advocate',
    commitmentLevel: 'Full-time',
    industries: ['LegalTech', 'AI'],
    profilePic: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1000&auto=format&fit=crop',
    coverPhoto: '',
    achievements: [],
    badges: [],
    reputationScore: 88,
    streakCount: 4,
    lastActiveAt: null as any,
    createdAt: null as any,
    socialLinks: {},
    isVisible: true,
    isBot: false,
    projects: [
      { name: 'AutoBrief', description: 'AI-driven legal brief generation.', role: 'CTO' }
    ],
    portfolioLinks: [],
    startupIdeas: [],
    resume: { shippedProducts: [], sideProjects: [], startupAttempts: [], hackathonWins: ['LawHack 2023'], buildStreaks: 2 },
    onboarded: true
  },
  {
    uid: 'demo9',
    displayName: 'Liam Wilson',
    age: 29,
    bio: 'Data Scientist. Love finding signal in noise. Expert in Kaggle competitions. Let\'s build something smart.',
    skills: ['Machine Learning', 'Data Viz', 'PyTorch'],
    interests: ['Big Data', 'Prediction', 'Gaming'],
    goals: 'Work on data-driven products',
    country: 'Australia',
    city: 'Sydney',
    experience: 'Senior Data Scientist',
    personalityType: 'Scientist',
    commitmentLevel: 'Full-time',
    industries: ['AI', 'Analytics'],
    profilePic: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=1000&auto=format&fit=crop',
    coverPhoto: '',
    achievements: [],
    badges: [],
    reputationScore: 93,
    streakCount: 33,
    lastActiveAt: null as any,
    createdAt: null as any,
    socialLinks: {},
    isVisible: true,
    isBot: false,
    projects: [
      { name: 'TradePredict', description: 'ML engine for predictive market analytics.', role: 'Lead Researcher' }
    ],
    portfolioLinks: [],
    startupIdeas: [],
    resume: { shippedProducts: [], sideProjects: [], startupAttempts: [], hackathonWins: ['Kaggle Master', 'DataCup Winner'], buildStreaks: 30 },
    onboarded: true
  },
  {
    uid: 'demo10',
    displayName: 'Chloe Smith',
    age: 25,
    bio: 'Community builder & Event organizer. Passionate about bringing people together through technology.',
    skills: ['Community Management', 'Events', 'Public Relations'],
    interests: ['Developer Relations', 'Events', 'SaaS'],
    goals: 'Build a massive global community',
    country: 'UK',
    city: 'Manchester',
    experience: 'Community Lead',
    personalityType: 'Helper',
    commitmentLevel: 'Full-time',
    industries: ['Web3', 'EdTech'],
    profilePic: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=1000&auto=format&fit=crop',
    coverPhoto: '',
    achievements: [],
    badges: [],
    reputationScore: 90,
    streakCount: 7,
    lastActiveAt: null as any,
    createdAt: null as any,
    socialLinks: {},
    isVisible: true,
    isBot: false,
    projects: [
      { name: 'ConnectConf', description: 'Tech conference for decentralized community builders.', role: 'Organizer' }
    ],
    portfolioLinks: [],
    startupIdeas: [],
    resume: { shippedProducts: [], sideProjects: [], startupAttempts: [], hackathonWins: [], buildStreaks: 5 },
    onboarded: true
  }
];

export const DEMO_POSTS: Post[] = [
  {
    id: 'demo-post-1',
    authorId: 'demo1',
    content: "Just launched the alpha for NeuralLink. It's a low-latency interface for real-time thought-to-text. Looking for feedback from other builders!",
    type: 'launch',
    timestamp: new Date(),
    likesCount: 24,
    commentsCount: 5
  },
  {
    id: 'demo-post-2',
    authorId: 'demo2',
    content: "Design system for 'Flux' is finally complete. 50+ components, fully responsive, and with a unique brutalist vibe. DM me if you need design help!",
    type: 'build',
    timestamp: new Date(),
    likesCount: 18,
    commentsCount: 3
  },
  {
    id: 'demo-post-3',
    authorId: 'demo3',
    content: "We just hit 10k users on the waitlist! Growth is exponential right now. Need a Scala/Backend wizard to help us scale the engine.",
    type: 'achievement',
    timestamp: new Date(),
    likesCount: 42,
    commentsCount: 12
  }
];
