import { Timestamp } from 'firebase/firestore';
import { UserProfile } from '../types';

const demoDate = Timestamp.fromDate(new Date('2026-01-01T00:00:00.000Z'));

const makeDemoBuilder = (profile: Partial<UserProfile> & Pick<UserProfile, 'uid' | 'displayName' | 'bio' | 'profilePic' | 'occupation' | 'city' | 'country' | 'age' | 'skills' | 'industries' | 'lookingFor'>): UserProfile => ({
  username: profile.displayName.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 18),
  profileLink: `linkup://profile/${profile.uid}`,
  photos: [profile.profilePic],
  company: '',
  interests: profile.industries || [],
  goals: (profile.lookingFor || []).join(', '),
  experience: 'Experienced',
  personalityType: 'Fast-paced • Collaborative',
  commitmentLevel: 'Full-time',
  ambition: 'High Ambition',
  reputationScore: 78,
  streakCount: 4,
  founderScore: 82,
  reputationMetrics: {
    reliability: 82,
    responseRate: 76,
    collaboration: 84,
    consistency: 79,
    completion: 81,
  },
  aiMatchInsights: 'Demo profile for swipe testing.',
  networkingIntent: 'Serious Builder',
  onboarded: true,
  isVisible: true,
  turboConnect: false,
  isBot: true,
  isOnline: false,
  lastActiveAt: demoDate,
  createdAt: demoDate,
  socialLinks: {},
  resume: {
    shippedProducts: [],
    sideProjects: [],
    startupAttempts: [],
    hackathonWins: [],
    buildStreaks: 2,
  },
  badges: ['Demo Builder'],
  projects: [],
  viewedBy: [],
  isStealthMode: false,
  hideOnlineStatus: false,
  hasExit: false,
  availability: 'Open to Networking',
  timezone: 'UTC+2',
  languages: ['English'],
  startupStage: 'MVP',
  fundingStage: 'Bootstrapped',
  workStyle: 'Fast-paced',
  education: '',
  remoteOnly: true,
  willingToRelocate: false,
  teamSizePreference: 'Small Team',
  circles: ['Demo Builders'],
  personalityAnswers: {},
  roleAnswers: {},
  ...profile,
});

const allDemoBuilders: UserProfile[] = [
  makeDemoBuilder({
    uid: 'demo-builder-amara',
    displayName: 'Amara Ncube',
    bio: 'AI product founder building tools for African creators and startup teams.',
    profilePic: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=900',
    occupation: 'Founder',
    company: 'CreatorFlow AI',
    city: 'Harare',
    country: 'Zimbabwe',
    age: 24,
    skills: ['Product Strategy', 'AI', 'Sales', 'Community'],
    industries: ['AI', 'Creator Economy', 'SaaS'],
    lookingFor: ['Technical Cofounder', 'AI Engineer', 'Startup Team'],
    startupStage: 'MVP',
    reputationScore: 88,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-kai',
    displayName: 'Kai Mensah',
    bio: 'Full-stack developer focused on fintech APIs, mobile apps, and clean backend systems.',
    profilePic: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=900',
    occupation: 'Backend Developer',
    company: 'PayNest',
    city: 'Accra',
    country: 'Ghana',
    age: 27,
    skills: ['Node.js', 'Python', 'Firebase', 'Fintech'],
    industries: ['Fintech', 'SaaS', 'AI'],
    lookingFor: ['Founder', 'Startup Team', 'Freelance Work'],
    workStyle: 'Structured',
    reputationScore: 84,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-lina',
    displayName: 'Lina Okafor',
    bio: 'UI/UX designer crafting premium mobile experiences for early-stage founders.',
    profilePic: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=900',
    occupation: 'Product Designer',
    company: 'PixelForge',
    city: 'Lagos',
    country: 'Nigeria',
    age: 23,
    skills: ['Figma', 'UI Design', 'UX Research', 'Branding'],
    industries: ['Social Platforms', 'SaaS', 'E-commerce'],
    lookingFor: ['Founder', 'Developer', 'Startup Team'],
    workStyle: 'Creative',
    reputationScore: 81,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-thabo',
    displayName: 'Thabo Mokoena',
    bio: 'AI engineer experimenting with retrieval systems and workflow automation.',
    profilePic: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=900',
    occupation: 'AI Engineer',
    company: 'NeuralWorks',
    city: 'Johannesburg',
    country: 'South Africa',
    age: 26,
    skills: ['AI/ML', 'Python', 'LangChain', 'Backend'],
    industries: ['AI', 'Healthtech', 'SaaS'],
    lookingFor: ['Founder', 'Cofounder', 'Technical Team'],
    startupStage: 'Idea stage',
    reputationScore: 86,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-sarah',
    displayName: 'Sarah Kim',
    bio: 'Growth marketer helping B2B SaaS startups find repeatable acquisition channels.',
    profilePic: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=900',
    occupation: 'Growth Marketer',
    company: 'LaunchLoop',
    city: 'Seoul',
    country: 'South Korea',
    age: 29,
    skills: ['Growth', 'SEO', 'Content Strategy', 'Analytics'],
    industries: ['SaaS', 'AI', 'Education'],
    lookingFor: ['Founder', 'Startup Team', 'Partnerships'],
    workStyle: 'Analytical',
    reputationScore: 83,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-diego',
    displayName: 'Diego Alvarez',
    bio: 'Mobile developer shipping React Native MVPs for founders in weeks, not months.',
    profilePic: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900',
    occupation: 'Mobile Developer',
    company: 'AppSprint',
    city: 'Madrid',
    country: 'Spain',
    age: 28,
    skills: ['React Native', 'Expo', 'TypeScript', 'Firebase'],
    industries: ['E-commerce', 'Social Platforms', 'SaaS'],
    lookingFor: ['Founder', 'Freelance Work', 'Startup Team'],
    reputationScore: 85,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-nadia',
    displayName: 'Nadia Patel',
    bio: 'Investor scout looking for high-signal student founders and technical teams.',
    profilePic: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=900',
    occupation: 'Investor',
    company: 'SeedSignal',
    city: 'London',
    country: 'United Kingdom',
    age: 31,
    skills: ['Deal Sourcing', 'Mentorship', 'Fundraising', 'Fintech'],
    industries: ['Fintech', 'AI', 'Healthtech'],
    lookingFor: ['Investment', 'Mentorship', 'Networking'],
    fundingStage: 'Angel-backed',
    reputationScore: 90,
    isVerified: true,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-zoe',
    displayName: 'Zoe Chen',
    bio: 'Frontend engineer obsessed with beautiful dashboards and fast web apps.',
    profilePic: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=900',
    occupation: 'Frontend Developer',
    company: 'DashCraft',
    city: 'Singapore',
    country: 'Singapore',
    age: 25,
    skills: ['React', 'Next.js', 'TypeScript', 'UI Design'],
    industries: ['SaaS', 'Fintech', 'AI'],
    lookingFor: ['Founder', 'Product Designer', 'Startup Team'],
    reputationScore: 82,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-eli',
    displayName: 'Eli Johnson',
    bio: 'Operator building systems for hiring, customer success, and founder productivity.',
    profilePic: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=900',
    occupation: 'Operator',
    company: 'OpsLab',
    city: 'Austin',
    country: 'United States',
    age: 30,
    skills: ['Operations', 'Hiring', 'Customer Success', 'Systems'],
    industries: ['SaaS', 'Creator Economy', 'Education'],
    lookingFor: ['Founder', 'Startup Team', 'Partnerships'],
    workStyle: 'Structured',
    reputationScore: 79,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-ayesha',
    displayName: 'Ayesha Khan',
    bio: 'Student founder prototyping edtech tools for peer learning and micro-courses.',
    profilePic: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=900',
    occupation: 'Student Founder',
    company: 'SkillNest',
    city: 'Dubai',
    country: 'UAE',
    age: 21,
    skills: ['Prototyping', 'Research', 'Community', 'No-code'],
    industries: ['EdTech', 'AI', 'Social Platforms'],
    lookingFor: ['Mentorship', 'Technical Cofounder', 'Networking'],
    education: 'Student',
    reputationScore: 77,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-mateo',
    displayName: 'Mateo Rossi',
    bio: 'Robotics builder mixing hardware, computer vision, and industrial automation.',
    profilePic: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=900',
    occupation: 'Robotics Engineer',
    company: 'RoboStack',
    city: 'Milan',
    country: 'Italy',
    age: 28,
    skills: ['Robotics', 'Python', 'Computer Vision', 'Hardware'],
    industries: ['Robotics', 'AI', 'Manufacturing'],
    lookingFor: ['Investor', 'Startup Team', 'Partnerships'],
    startupStage: 'Early traction',
    reputationScore: 87,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-imani',
    displayName: 'Imani Brooks',
    bio: 'Brand strategist helping founders turn raw ideas into sharp market positioning.',
    profilePic: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=900',
    occupation: 'Brand Strategist',
    company: 'Signal Studio',
    city: 'Toronto',
    country: 'Canada',
    age: 27,
    skills: ['Branding', 'Positioning', 'Content', 'Go-to-market'],
    industries: ['Fashion Tech', 'Creator Economy', 'E-commerce'],
    lookingFor: ['Founder', 'Partnerships', 'Freelance Work'],
    workStyle: 'Creative',
    reputationScore: 80,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-hugo',
    displayName: 'Hugo Silva',
    bio: 'Cybersecurity developer building secure auth, compliance tooling, and privacy-first products.',
    profilePic: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=900',
    occupation: 'Cybersecurity Developer',
    company: 'VaultLayer',
    city: 'Lisbon',
    country: 'Portugal',
    age: 32,
    skills: ['Cybersecurity', 'Backend', 'Auth', 'Compliance'],
    industries: ['Cybersecurity', 'Fintech', 'SaaS'],
    lookingFor: ['Founder', 'Investor', 'Startup Team'],
    reputationScore: 89,
    isVerified: true,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-priya',
    displayName: 'Priya Raman',
    bio: 'Product manager turning vague startup ideas into MVP roadmaps and weekly shipping cycles.',
    profilePic: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=900',
    occupation: 'Product Manager',
    company: 'MVP Map',
    city: 'Bengaluru',
    country: 'India',
    age: 29,
    skills: ['Product Management', 'Roadmapping', 'User Research', 'Analytics'],
    industries: ['Healthtech', 'SaaS', 'AI'],
    lookingFor: ['Developer', 'Founder', 'Startup Team'],
    workStyle: 'Analytical',
    reputationScore: 86,
  }),
  makeDemoBuilder({
    uid: 'demo-builder-noah',
    displayName: 'Noah Williams',
    bio: 'Sales-led founder validating B2B workflow products with cold outreach and customer interviews.',
    profilePic: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=900',
    occupation: 'Founder',
    company: 'PipelineOS',
    city: 'Cape Town',
    country: 'South Africa',
    age: 26,
    skills: ['Sales', 'Customer Discovery', 'B2B SaaS', 'Partnerships'],
    industries: ['SaaS', 'AI', 'Productivity'],
    lookingFor: ['Technical Cofounder', 'Backend Developer', 'Investor'],
    startupStage: 'Idea stage',
    reputationScore: 82,
  }),
];

export const demoBuilders: UserProfile[] = allDemoBuilders.slice(0, 1);

export function isDemoBuilder(profile?: Pick<UserProfile, 'uid' | 'isBot'> | null) {
  return Boolean(profile?.isBot || String(profile?.uid || '').startsWith('demo-builder-'));
}
